sudo: required

services:
  - docker

jobs:
  include:
    - stage: docker
      script:
        - docker login -u="$DOCKERHUB_USERNAME" -p="$DOCKERHUB_PASSWORD"
        - "docker build . -t LarsBaertschi/nairi-wp"
        - "docker push LarsBaertschi/nairi-wp"

stages:
  - docker
